repos:
  - repo: local
    hooks:
      - id: rustfmt
        name: rustfmt
        description: Check if all files follow the rustfmt style
        entry: cargo fmt --all -- --check --color always
        language: system
        pass_filenames: false
      - id: rustclippy
        name: rustclippy
        description: run cargo clippy
        entry: cargo clippy --workspace -- -D warnings
        language: system
        pass_filenames: false