name: Check fmt

on:
    pull_request:
    push:
        branches: ["master", "develop"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check_format:
        name: Check fmt
        runs-on: ubuntu-latest
        steps:
            - uses: actions/cache@v3
              with:
                path: |
                    ~/.cargo/bin/
                    ~/.cargo/registry/index/
                    ~/.cargo/registry/cache/
                    ~/.cargo/git/db/
                    target/
            - uses: actions/checkout@v2
            - name: Check fmt
              run: cargo fmt -- --verbose --check --color auto

