on:
    push:
        branches: ["develop", "auto-release"] # auto-release only for testing

jobs:
    test:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            toolchain: [stable]
        name: Run tests
        runs-on: ${{ matrix.os }}
        steps:
            - name: Install latest ${{ matrix.toolchain }}
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.toolchain }}
            - uses: actions/checkout@v3
            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - name: Compile
              run: cargo build --release
            - uses: actions/upload-artifact@v3
              with:
                name: Alltrader-${{ runner.os }}
                path: |
                  target/release/trader
                  target/release/trader.exe