name: Tests

on:
    pull_request:
    push:
        branches: ["master", "develop"]

env:
    CARGO_TERM_COLOR: always

jobs:
    test:
        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            toolchain: [stable]
        name: Run tests
        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v2
            - name: Install latest ${{ matrix.toolchain }}
              uses: actions-rs/toolchain@v1
              with:
                toolchain: ${{ matrix.toolchain }}
            - uses: actions/cache@v3
              with:
                path: |
                  ~/.cargo/bin/
                  ~/.cargo/registry/index/
                  ~/.cargo/registry/cache/
                  ~/.cargo/git/db/
                  target/
                key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            - uses: actions/checkout@v2
            - name: Run tests
              run: cargo test --verbose

